version: '{build}'
platform:
  - x86
  - x64
configuration:
  - Release
clone_folder: C:\ccaligner
clone_depth: 1
install:
  - mkdir build && cd build
  - cmake ../src/
build:
  project: build/ccaligner.sln
  verbosity: minimal
on_success:
  - pwd
  - dir c:\ccaligner\build\