version: '{build}'
platform:
  - Win32
  - Win64
configuration: Release
clone_folder: C:\ccaligner
clone_depth: 1
install:
  - mkdir build && cd build
  - if %PLATFORM% equ x86 cmake -G "Visual Studio 14 2015" ../src/
  - if %PLATFORM% equ x64 cmake -G "Visual Studio 14 2015 Win64" ../src/
build:
  project: build/ccaligner.sln
  verbosity: minimal
on_success:
  - pwd
  - dir c:\ccaligner\build\
  - mkdir release
  - copy build\Release\ccaligner.exe release\
  - xcopy license\ release\
  - xcopy install\model release\ /s /e
  - 7z a c:\ccaligner.zip .\release > nul