version: '{build}'
platform:
  - Win32
  - x64
configuration: Release
clone_folder: C:\ccaligner
clone_depth: 1
environment:
  global:
    PYTHON: "C:\\Python26-x64"
    PYTHON_VERSION: "2.6.x"
    PYTHON_ARCH: "64"
install:
  - mkdir build && cd build
  - if %PLATFORM% equ Win32 (cmake -G "Visual Studio 14 2015" ../src/) else (cmake -G "Visual Studio 14 2015 Win64" ../src/)
build:
  project: build/ccaligner.sln
  verbosity: minimal
