version: '{build}'
platform:
  - Win32
  - Win64
configuration: Release
clone_folder: C:\ccaligner
clone_depth: 1
install:
  - mkdir build && cd build
  - if %PLATFORM% equ Win32 (cmake -G "Visual Studio 14 2015" ../src/) else (cmake -G "Visual Studio 14 2015 Win64" ../src/)
build:
  project: build/ccaligner.sln
  verbosity: minimal
on_success:
  - cd C:\ccaligner
  - mkdir release
  - copy build\Release\ccaligner.exe release\
  - xcopy license release
  - xcopy install\model release /s /e
  - xcopy install\g2p-seq2seq-cmudict release /s /e
  - copy install\quick_lm.pl release /s /e
  # perl, dependencies
  - 7z a ccaligner.zip .\release > nul
  - if %PLATFORM% equ x64 rename ccaligner.zip ccaligner_x64.zip
  - if %PLATFORM% equ x64 (appveyor PushArtifact ccaligner_x64.zip) else (appveyor PushArtifact ccaligner.zip)