version: '{build}'
platform:
  - Win32
  - x64
configuration: Release
clone_folder: C:\ccaligner
clone_depth: 1
environment:
  global:
    PYTHON: "C:\\Python26-x64"
    PYTHON_VERSION: "2.6.x"
    PYTHON_ARCH: "64"
install:
  - mkdir build && cd build
  - if %PLATFORM% equ Win32 (cmake -G "Visual Studio 14 2015" ../src/) else (cmake -G "Visual Studio 14 2015 Win64" ../src/)
build:
  project: build/ccaligner.sln
  verbosity: minimal
on_success:
  - cd C:\ccaligner
  - mkdir release > nul
  - copy build\Release\ccaligner.exe release\ > nul
  - xcopy license release > nul
  - xcopy install\model release /s /e > nul
  - xcopy install\g2p-seq2seq-cmudict release /s /e > nul
  - copy install\quick_lm.pl release\ > nul
  # perl, dependencies
  # g2p-seq2seq
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py'
  - C:\Python26-x64\python.exe get-pip.py
  - C:\Python26-x64\python.exe -m pip install tensorflow==1.0.0
  - git clone https://github.com/cmusphinx/g2p-seq2seq.git
  - cd g2p-seq2seq && python setup.py install && cd ..
  # cmuclmtk
  - ps: Start-FileDownload 'https://downloads.sourceforge.net/project/cmusphinx/cmuclmtk/0.7/cmuclmtk-0.7.tar.gz'
  - tar xzvf cmuclmtk-0.7.tar.gz
  - dir
  - cd cmuclmtk-0.7
  - dir
  - 7z a ccaligner.zip .\release > nul
  - if %PLATFORM% equ x64 rename ccaligner.zip ccaligner_x64.zip
  - if %PLATFORM% equ x64 (appveyor PushArtifact ccaligner_x64.zip) else (appveyor PushArtifact ccaligner.zip)